import React, {PropTypes} from 'react';
import {connect} from 'react-redux';
import Select from 'react-select';
import * as carActions from '../actions/carActions';
import {bindActionCreators} from 'redux';

class CarsContainer extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      brand: null,
      model: null,
      year: null,
      fuel: null,
      bodyType: null,
      KW: null,
      milage: null,
      autoTransmission: false,
      price: 0
    };
  }

  getCarRate = () => {
    let car = {
      Year: this.state.year.value,
      Brand: this.state.brand.value,
      Model: this.state.model.value,
      Fuel: this.state.fuel.value,
      BodyType: this.state.bodyType.value,
      KW: this.state.KW.value,
      Milage: this.state.milage.value,
      AutomaticTransmission: this.state.autoTransmission ? 1 : 0,
    };

    this.props.carActions.carRate(car);
  };

  allValuesExist = () => {
    let result = !!this.state.brand &&
      !!this.state.model &&
      !!this.state.year &&
      !!this.state.fuel &&
      !!this.state.bodyType &&
      !!this.state.KW &&
      !!this.state.milage;
    return result;
  };



  render() {
    return (
      <div>
        <h1>Car data</h1>
        <form onSubmit={event => event.preventDefault()}>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.brand}
                    options={carBrands}
                    onChange={value => this.setState({brand: value})}
                    clearable={true}
                    placeholder={"Brand"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.model}
                    options={getModels(this.state.brand)}
                    onChange={value => this.setState({model: value})}
                    clearable={true}
                    placeholder={"Model"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.year}
                    options={carYears()}
                    onChange={value => this.setState({year: value})}
                    clearable={true}
                    placeholder={"Year"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.fuel}
                    options={carFuels}
                    onChange={value => this.setState({fuel: value})}
                    clearable={true}
                    placeholder={"Fuel"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.bodyType}
                    options={carBodyTypes}
                    onChange={value => this.setState({bodyType: value})}
                    clearable={true}
                    placeholder={"Body Type"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.KW}
                    options={carKw()}
                    onChange={value => this.setState({KW: value})}
                    clearable={true}
                    placeholder={"Power (KW)"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <Select className="carForm-select"
                    value={this.state.milage}
                    options={carMilages()}
                    onChange={value => this.setState({milage: value})}
                    clearable={true}
                    placeholder={"Milage (km)"}
                    required={true}
            />
          </div>
          <div className="carForm">
            <input type="checkbox" value={this.state.autoTransmission}
                   onChange={() => this.setState({autoTransmission: !this.state.autoTransmission})}/>Automatic transmission<br/>
          </div>
          <div className="carForm">
            <input type="submit" value="Submit" onClick={() => this.getCarRate()} disabled={!this.allValuesExist()}/>
          </div>
        </form>
        { this.props.price !== 0 && <h1>Estimated price: {this.props.price}</h1>}
      </div>
    );
  }
}


CarsContainer.propTypes = {
  carActions: PropTypes.object.isRequired,
  price: PropTypes.number.isRequired,

};

function mapStateToProps(state) {
  return {
    price: state.car,
  };
}

function mapDispatchToProps(dispatch) {
  return {
    carActions: bindActionCreators(carActions, dispatch)
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(CarsContainer);

let getModels = brand => {
  if(!brand)
    return [];
  return carModel.filter(v => {return v.brand === brand.value;});
};

let carYears = () => {
  return Array.apply(0, Array(13))
    .map(function (element, index) {
      return {value: index + 2000, label: index + 2000};
    });
};

let carKw = () => {
  return Array.apply(0, Array(208))
    .map(function (element, index) {
      return {value: index + 42, label: index + 42};
    });
};

let carMilages = () => {
  return Array.apply(0, Array(146))
    .map(function (element, index) {
      return {value: (index + 5) * 2000, label: (index + 5) * 2000};
    });
};

const carBodyTypes = [
  {value: "Universalas", label: "Universalas"},
  {value: "Sedanas", label: "Sedanas"},
  {value: "Hečbekas", label: "Hečbekas"},
  {value: "Visureigis", label: "Visureigis"},
  {value: "Vienatūris", label: "Vienatūris"},
  {value: "Kupė(Coupe)", label: "Kupė(Coupe)"},
  {value: "Kabrioletas/Roadster", label: "Kabrioletas/Roadster"},
  {value: "Komercinis", label: "Komercinis"},
  {value: "Pikapas", label: "Pikapas"},
  {value: "Limuzinas", label: "Limuzinas"}
];

const carFuels = [
  {value: "Dyzelinas", label: "Dyzelinas"},
  {value: "Benzinas", label: "Benzinas"},
  {value: "Benzinas/dujos", label: "Benzinas/dujos"},
  {value: "Benzinas/elektra", label: "Benzinas/elektra"},
  {value: "Elektra", label: "Elektra"},
  {value: "Dyzelinas/elektra", label: "Dyzelinas/elektra"},
  {value: "Dyzelinas/dujos", label: "Dyzelinas/dujos"}
];

const carBrands = [
  { value: "Acura", label:"Acura" },
  { value: "Aixam", label:"Aixam" },
  { value: "Alfa Romeo", label:"Alfa Romeo" },
  { value: "Alpina", label:"Alpina" },
  { value: "Aston Martin", label:"Aston Martin" },
  { value: "Audi", label:"Audi" },
  { value: "Austin Rover", label:"Austin Rover" },
  { value: "Bentley", label:"Bentley" },
  { value: "BMW", label:"BMW" },
  { value: "Buick", label:"Buick" },
  { value: "Cadillac", label:"Cadillac" },
  { value: "Chevrolet", label:"Chevrolet" },
  { value: "Chrysler", label:"Chrysler" },
  { value: "Citroen", label:"Citroen" },
  { value: "Cobra", label:"Cobra" },
  { value: "Dacia", label:"Dacia" },
  { value: "Daewoo", label:"Daewoo" },
  { value: "DAF", label:"DAF" },
  { value: "Daihatsu", label:"Daihatsu" },
  { value: "Dodge", label:"Dodge" },
  { value: "Ferrari", label:"Ferrari" },
  { value: "Fiat", label:"Fiat" },
  { value: "Ford", label:"Ford" },
  { value: "GAZ", label:"GAZ" },
  { value: "GMC", label:"GMC" },
  { value: "Great Wall", label:"Great Wall" },
  { value: "Honda", label:"Honda" },
  { value: "Hummer", label:"Hummer" },
  { value: "Hyundai", label:"Hyundai" },
  { value: "Infiniti", label:"Infiniti" },
  { value: "Isuzu", label:"Isuzu" },
  { value: "Iveco", label:"Iveco" },
  { value: "Jaguar", label:"Jaguar" },
  { value: "Jeep", label:"Jeep" },
  { value: "Kia", label:"Kia" },
  { value: "Kita", label:"Kita" },
  { value: "Lada", label:"Lada" },
  { value: "Lancia", label:"Lancia" },
  { value: "Land Rover", label:"Land Rover" },
  { value: "Lexus", label:"Lexus" },
  { value: "Ligier", label:"Ligier" },
  { value: "Lincoln", label:"Lincoln" },
  { value: "LuAZ", label:"LuAZ" },
  { value: "Maserati", label:"Maserati" },
  { value: "Mazda", label:"Mazda" },
  { value: "Mercedes-Benz", label:"Mercedes-Benz" },
  { value: "Mercury", label:"Mercury" },
  { value: "MG", label:"MG" },
  { value: "Microcar", label:"Microcar" },
  { value: "Mini", label:"Mini" },
  { value: "Mitsubishi", label:"Mitsubishi" },
  { value: "Moskvich", label:"Moskvich" },
  { value: "Nissan", label:"Nissan" },
  { value: "Oldsmobile", label:"Oldsmobile" },
  { value: "Opel", label:"Opel" },
  { value: "Peugeot", label:"Peugeot" },
  { value: "Plymouth", label:"Plymouth" },
  { value: "Pontiac", label:"Pontiac" },
  { value: "Porsche", label:"Porsche" },
  { value: "Proton", label:"Proton" },
  { value: "Renault", label:"Renault" },
  { value: "Rolls-Royce", label:"Rolls-Royce" },
  { value: "Rover", label:"Rover" },
  { value: "Saab", label:"Saab" },
  { value: "Saturn", label:"Saturn" },
  { value: "Scion", label:"Scion" },
  { value: "Seat", label:"Seat" },
  { value: "Secma", label:"Secma" },
  { value: "Shuanghuan", label:"Shuanghuan" },
  { value: "Skoda", label:"Skoda" },
  { value: "Smart", label:"Smart" },
  { value: "SsangYong", label:"SsangYong" },
  { value: "Subaru", label:"Subaru" },
  { value: "Suzuki", label:"Suzuki" },
  { value: "Tata", label:"Tata" },
  { value: "Tesla", label:"Tesla" },
  { value: "Toyota", label:"Toyota" },
  { value: "Trabant", label:"Trabant" },
  { value: "UAZ", label:"UAZ" },
  { value: "Vauxhall", label:"Vauxhall" },
  { value: "Volkswagen", label:"Volkswagen" },
  { value: "Volvo", label:"Volvo" },
  { value: "Wanderer", label:"Wanderer" },
  { value: "ZAZ", label:"ZAZ" }
];

const carModel = [
  {brand:"Acura", value:"ILX", label:"ILX"},
  {brand:"Acura", value:"MDX", label:"MDX"},
  {brand:"Acura", value:"RL", label:"RL"},
  {brand:"Acura", value:"TSX", label:"TSX"},
  {brand:"Acura", value:"ZDX", label:"ZDX"},
  {brand:"Aixam", value:"400", label:"400"},
  {brand:"Aixam", value:"A751", label:"A751"},
  {brand:"Aixam", value:"Kita", label:"Kita"},
  {brand:"Aixam", value:"Miesto", label:"Miesto"},
  {brand:"Aixam", value:"Scouty", label:"Scouty"},
  {brand:"Alfa Romeo", value:"146", label:"146"},
  {brand:"Alfa Romeo", value:"147", label:"147"},
  {brand:"Alfa Romeo", value:"155", label:"155"},
  {brand:"Alfa Romeo", value:"156", label:"156"},
  {brand:"Alfa Romeo", value:"159", label:"159"},
  {brand:"Alfa Romeo", value:"166", label:"166"},
  {brand:"Alfa Romeo", value:"Brera", label:"Brera"},
  {brand:"Alfa Romeo", value:"Crosswagon Q4", label:"Crosswagon Q4"},
  {brand:"Alfa Romeo", value:"Giulia", label:"Giulia"},
  {brand:"Alfa Romeo", value:"Giulietta", label:"Giulietta"},
  {brand:"Alfa Romeo", value:"GT", label:"GT"},
  {brand:"Alfa Romeo", value:"GTV", label:"GTV"},
  {brand:"Alfa Romeo", value:"Mito", label:"Mito"},
  {brand:"Alfa Romeo", value:"Spider", label:"Spider"},
  {brand:"Alpina", value:"B10", label:"B10"},
  {brand:"Alpina", value:"B3", label:"B3"},
  {brand:"Alpina", value:"B6", label:"B6"},
  {brand:"Aston Martin", value:"Vantage", label:"Vantage"},
  {brand:"Audi", value:"", label:""},
  {brand:"Audi", value:"100", label:"100"},
  {brand:"Audi", value:"200", label:"200"},
  {brand:"Audi", value:"80", label:"80"},
  {brand:"Audi", value:"90", label:"90"},
  {brand:"Audi", value:"A1", label:"A1"},
  {brand:"Audi", value:"A2", label:"A2"},
  {brand:"Audi", value:"A3", label:"A3"},
  {brand:"Audi", value:"A4", label:"A4"},
  {brand:"Audi", value:"A4 ALLROAD", label:"A4 ALLROAD"},
  {brand:"Audi", value:"A5", label:"A5"},
  {brand:"Audi", value:"A5 SPORTBACK", label:"A5 SPORTBACK"},
  {brand:"Audi", value:"A6", label:"A6"},
  {brand:"Audi", value:"A6 ALLROAD", label:"A6 ALLROAD"},
  {brand:"Audi", value:"A7 SPORTBACK", label:"A7 SPORTBACK"},
  {brand:"Audi", value:"A8", label:"A8"},
  {brand:"Audi", value:"Cabriolet", label:"Cabriolet"},
  {brand:"Audi", value:"Kupė (Coupe)", label:"Kupė (Coupe)"},
  {brand:"Audi", value:"Q2", label:"Q2"},
  {brand:"Audi", value:"Q3", label:"Q3"},
  {brand:"Audi", value:"Q5", label:"Q5"},
  {brand:"Audi", value:"Q7", label:"Q7"},
  {brand:"Audi", value:"RS4", label:"RS4"},
  {brand:"Audi", value:"RS5", label:"RS5"},
  {brand:"Audi", value:"RS6", label:"RS6"},
  {brand:"Audi", value:"S3", label:"S3"},
  {brand:"Audi", value:"S4", label:"S4"},
  {brand:"Audi", value:"S5", label:"S5"},
  {brand:"Audi", value:"S6", label:"S6"},
  {brand:"Audi", value:"S7", label:"S7"},
  {brand:"Audi", value:"S8", label:"S8"},
  {brand:"Audi", value:"SQ5", label:"SQ5"},
  {brand:"Audi", value:"TT", label:"TT"},
  {brand:"Austin Rover", value:"Kita", label:"Kita"},
  {brand:"Bentley", value:"Arnage", label:"Arnage"},
  {brand:"Bentley", value:"Continental", label:"Continental"},
  {brand:"Bentley", value:"Eight", label:"Eight"},
  {brand:"Bentley", value:"Flying Spur", label:"Flying Spur"},
  {brand:"Bentley", value:"Kita", label:"Kita"},
  {brand:"BMW", value:"114", label:"114"},
  {brand:"BMW", value:"116", label:"116"},
  {brand:"BMW", value:"118", label:"118"},
  {brand:"BMW", value:"120", label:"120"},
  {brand:"BMW", value:"123", label:"123"},
  {brand:"BMW", value:"128", label:"128"},
  {brand:"BMW", value:"135", label:"135"},
  {brand:"BMW", value:"216 Active Tourer", label:"216 Active Tourer"},
  {brand:"BMW", value:"218 Gran Tourer", label:"218 Gran Tourer"},
  {brand:"BMW", value:"220 Active Tourer", label:"220 Active Tourer"},
  {brand:"BMW", value:"225", label:"225"},
  {brand:"BMW", value:"228", label:"228"},
  {brand:"BMW", value:"316", label:"316"},
  {brand:"BMW", value:"318", label:"318"},
  {brand:"BMW", value:"318 Gran turismo", label:"318 Gran turismo"},
  {brand:"BMW", value:"320", label:"320"},
  {brand:"BMW", value:"320 Gran turismo", label:"320 Gran turismo"},
  {brand:"BMW", value:"323", label:"323"},
  {brand:"BMW", value:"324", label:"324"},
  {brand:"BMW", value:"325", label:"325"},
  {brand:"BMW", value:"325 Gran turismo", label:"325 Gran turismo"},
  {brand:"BMW", value:"328", label:"328"},
  {brand:"BMW", value:"328 Gran turismo", label:"328 Gran turismo"},
  {brand:"BMW", value:"330", label:"330"},
  {brand:"BMW", value:"330 Gran turismo", label:"330 Gran turismo"},
  {brand:"BMW", value:"335", label:"335"},
  {brand:"BMW", value:"335 Gran turismo", label:"335 Gran turismo"},
  {brand:"BMW", value:"340", label:"340"},
  {brand:"BMW", value:"418 Gran Coupe", label:"418 Gran Coupe"},
  {brand:"BMW", value:"420", label:"420"},
  {brand:"BMW", value:"420 Gran Coupe", label:"420 Gran Coupe"},
  {brand:"BMW", value:"428", label:"428"},
  {brand:"BMW", value:"428 Gran Coupe", label:"428 Gran Coupe"},
  {brand:"BMW", value:"435", label:"435"},
  {brand:"BMW", value:"435 Gran Coupe", label:"435 Gran Coupe"},
  {brand:"BMW", value:"518", label:"518"},
  {brand:"BMW", value:"520", label:"520"},
  {brand:"BMW", value:"520 Gran turismo", label:"520 Gran turismo"},
  {brand:"BMW", value:"523", label:"523"},
  {brand:"BMW", value:"525", label:"525"},
  {brand:"BMW", value:"528", label:"528"},
  {brand:"BMW", value:"530", label:"530"},
  {brand:"BMW", value:"530 Gran Turismo", label:"530 Gran Turismo"},
  {brand:"BMW", value:"535", label:"535"},
  {brand:"BMW", value:"535 Gran Turismo", label:"535 Gran Turismo"},
  {brand:"BMW", value:"540", label:"540"},
  {brand:"BMW", value:"545", label:"545"},
  {brand:"BMW", value:"550", label:"550"},
  {brand:"BMW", value:"550 Gran turismo", label:"550 Gran turismo"},
  {brand:"BMW", value:"630", label:"630"},
  {brand:"BMW", value:"633", label:"633"},
  {brand:"BMW", value:"635", label:"635"},
  {brand:"BMW", value:"640", label:"640"},
  {brand:"BMW", value:"640 Gran Coupe", label:"640 Gran Coupe"},
  {brand:"BMW", value:"645", label:"645"},
  {brand:"BMW", value:"650", label:"650"},
  {brand:"BMW", value:"650 Gran Coupe", label:"650 Gran Coupe"},
  {brand:"BMW", value:"725", label:"725"},
  {brand:"BMW", value:"728", label:"728"},
  {brand:"BMW", value:"730", label:"730"},
  {brand:"BMW", value:"735", label:"735"},
  {brand:"BMW", value:"740", label:"740"},
  {brand:"BMW", value:"745", label:"745"},
  {brand:"BMW", value:"750", label:"750"},
  {brand:"BMW", value:"760", label:"760"},
  {brand:"BMW", value:"840", label:"840"},
  {brand:"BMW", value:"Active Hybrid 3", label:"Active Hybrid 3"},
  {brand:"BMW", value:"Active Hybrid 5", label:"Active Hybrid 5"},
  {brand:"BMW", value:"Active Hybrid 7", label:"Active Hybrid 7"},
  {brand:"BMW", value:"i3", label:"i3"},
  {brand:"BMW", value:"Kita", label:"Kita"},
  {brand:"BMW", value:"M2", label:"M2"},
  {brand:"BMW", value:"M235", label:"M235"},
  {brand:"BMW", value:"M3", label:"M3"},
  {brand:"BMW", value:"M4", label:"M4"},
  {brand:"BMW", value:"M5", label:"M5"},
  {brand:"BMW", value:"M550", label:"M550"},
  {brand:"BMW", value:"M6", label:"M6"},
  {brand:"BMW", value:"X1", label:"X1"},
  {brand:"BMW", value:"X3", label:"X3"},
  {brand:"BMW", value:"X4", label:"X4"},
  {brand:"BMW", value:"X5", label:"X5"},
  {brand:"BMW", value:"X5 M", label:"X5 M"},
  {brand:"BMW", value:"X6", label:"X6"},
  {brand:"BMW", value:"X6 M", label:"X6 M"},
  {brand:"BMW", value:"Z3", label:"Z3"},
  {brand:"BMW", value:"Z4", label:"Z4"},
  {brand:"Buick", value:"Encore", label:"Encore"},
  {brand:"Buick", value:"Kita", label:"Kita"},
  {brand:"Buick", value:"Le Sabre", label:"Le Sabre"},
  {brand:"Buick", value:"Regal", label:"Regal"},
  {brand:"Cadillac", value:"ATS", label:"ATS"},
  {brand:"Cadillac", value:"BLS", label:"BLS"},
  {brand:"Cadillac", value:"CTS", label:"CTS"},
  {brand:"Cadillac", value:"DeVille", label:"DeVille"},
  {brand:"Cadillac", value:"Eldorado", label:"Eldorado"},
  {brand:"Cadillac", value:"Escalade", label:"Escalade"},
  {brand:"Cadillac", value:"Fleetwood", label:"Fleetwood"},
  {brand:"Cadillac", value:"Kita", label:"Kita"},
  {brand:"Cadillac", value:"Seville", label:"Seville"},
  {brand:"Cadillac", value:"SRX", label:"SRX"},
  {brand:"Cadillac", value:"STS", label:"STS"},
  {brand:"Chevrolet", value:"Alero", label:"Alero"},
  {brand:"Chevrolet", value:"Astro", label:"Astro"},
  {brand:"Chevrolet", value:"Avalanche", label:"Avalanche"},
  {brand:"Chevrolet", value:"Aveo", label:"Aveo"},
  {brand:"Chevrolet", value:"Blazer", label:"Blazer"},
  {brand:"Chevrolet", value:"Camaro", label:"Camaro"},
  {brand:"Chevrolet", value:"Captiva", label:"Captiva"},
  {brand:"Chevrolet", value:"Chevy Van", label:"Chevy Van"},
  {brand:"Chevrolet", value:"Corvette", label:"Corvette"},
  {brand:"Chevrolet", value:"Cruze", label:"Cruze"},
  {brand:"Chevrolet", value:"Epica", label:"Epica"},
  {brand:"Chevrolet", value:"Express", label:"Express"},
  {brand:"Chevrolet", value:"HHR", label:"HHR"},
  {brand:"Chevrolet", value:"Impala", label:"Impala"},
  {brand:"Chevrolet", value:"Kalos", label:"Kalos"},
  {brand:"Chevrolet", value:"Lacetti", label:"Lacetti"},
  {brand:"Chevrolet", value:"Malibu", label:"Malibu"},
  {brand:"Chevrolet", value:"Matiz", label:"Matiz"},
  {brand:"Chevrolet", value:"Nubira", label:"Nubira"},
  {brand:"Chevrolet", value:"Orlando", label:"Orlando"},
  {brand:"Chevrolet", value:"Priemiestinis", label:"Priemiestinis"},
  {brand:"Chevrolet", value:"Rezzo", label:"Rezzo"},
  {brand:"Chevrolet", value:"Silverado", label:"Silverado"},
  {brand:"Chevrolet", value:"Spark", label:"Spark"},
  {brand:"Chevrolet", value:"SSR", label:"SSR"},
  {brand:"Chevrolet", value:"Tahoe", label:"Tahoe"},
  {brand:"Chevrolet", value:"Trans Sport", label:"Trans Sport"},
  {brand:"Chevrolet", value:"Traverse", label:"Traverse"},
  {brand:"Chevrolet", value:"Trax", label:"Trax"},
  {brand:"Chevrolet", value:"Volt", label:"Volt"},
  {brand:"Chrysler", value:"", label:""},
  {brand:"Chrysler", value:"200", label:"200"},
  {brand:"Chrysler", value:"300C", label:"300C"},
  {brand:"Chrysler", value:"300M", label:"300M"},
  {brand:"Chrysler", value:"Concorde", label:"Concorde"},
  {brand:"Chrysler", value:"Crossfire", label:"Crossfire"},
  {brand:"Chrysler", value:"Grand Voyager", label:"Grand Voyager"},
  {brand:"Chrysler", value:"Imperial", label:"Imperial"},
  {brand:"Chrysler", value:"Kita", label:"Kita"},
  {brand:"Chrysler", value:"New Yorker", label:"New Yorker"},
  {brand:"Chrysler", value:"Pacifica", label:"Pacifica"},
  {brand:"Chrysler", value:"Prowler", label:"Prowler"},
  {brand:"Chrysler", value:"PT Cruiser", label:"PT Cruiser"},
  {brand:"Chrysler", value:"Sebring", label:"Sebring"},
  {brand:"Chrysler", value:"Stratus", label:"Stratus"},
  {brand:"Chrysler", value:"Town & Country", label:"Town & Country"},
  {brand:"Chrysler", value:"Vision", label:"Vision"},
  {brand:"Chrysler", value:"Voyager", label:"Voyager"},
  {brand:"Citroen", value:"Berlingo", label:"Berlingo"},
  {brand:"Citroen", value:"C1", label:"C1"},
  {brand:"Citroen", value:"C2", label:"C2"},
  {brand:"Citroen", value:"C3", label:"C3"},
  {brand:"Citroen", value:"C3 Picasso  ", label:"C3 Picasso  "},
  {brand:"Citroen", value:"C3 Pluriel", label:"C3 Pluriel"},
  {brand:"Citroen", value:"C4", label:"C4"},
  {brand:"Citroen", value:"C4 Aircross", label:"C4 Aircross"},
  {brand:"Citroen", value:"C4 Cactus", label:"C4 Cactus"},
  {brand:"Citroen", value:"C4 Picasso", label:"C4 Picasso"},
  {brand:"Citroen", value:"C5", label:"C5"},
  {brand:"Citroen", value:"C6", label:"C6"},
  {brand:"Citroen", value:"C8", label:"C8"},
  {brand:"Citroen", value:"C-Crosser", label:"C-Crosser"},
  {brand:"Citroen", value:"C-Elysee", label:"C-Elysee"},
  {brand:"Citroen", value:"DS3", label:"DS3"},
  {brand:"Citroen", value:"DS4", label:"DS4"},
  {brand:"Citroen", value:"DS5", label:"DS5"},
  {brand:"Citroen", value:"Evasion", label:"Evasion"},
  {brand:"Citroen", value:"fsdf", label:"fsdf"},
  {brand:"Citroen", value:"Grand C4 Picasso", label:"Grand C4 Picasso"},
  {brand:"Citroen", value:"Jumper", label:"Jumper"},
  {brand:"Citroen", value:"Jumpy", label:"Jumpy"},
  {brand:"Citroen", value:"Kita", label:"Kita"},
  {brand:"Citroen", value:"Nemo", label:"Nemo"},
  {brand:"Citroen", value:"Xantia", label:"Xantia"},
  {brand:"Citroen", value:"Xsara", label:"Xsara"},
  {brand:"Citroen", value:"Xsara Picasso", label:"Xsara Picasso"},
  {brand:"Cobra", value:"AC", label:"AC"},
  {brand:"Dacia", value:"Dokker", label:"Dokker"},
  {brand:"Dacia", value:"Duster", label:"Duster"},
  {brand:"Dacia", value:"Lodgy", label:"Lodgy"},
  {brand:"Dacia", value:"Logan", label:"Logan"},
  {brand:"Dacia", value:"Sandero", label:"Sandero"},
  {brand:"Daewoo", value:"Kalos", label:"Kalos"},
  {brand:"Daewoo", value:"Korando", label:"Korando"},
  {brand:"Daewoo", value:"Matiz", label:"Matiz"},
  {brand:"Daewoo", value:"Nubira", label:"Nubira"},
  {brand:"DAF", value:"55", label:"55"},
  {brand:"Daihatsu", value:"Copen", label:"Copen"},
  {brand:"Daihatsu", value:"Cuore", label:"Cuore"},
  {brand:"Daihatsu", value:"Feroza", label:"Feroza"},
  {brand:"Daihatsu", value:"Materia", label:"Materia"},
  {brand:"Daihatsu", value:"Move", label:"Move"},
  {brand:"Daihatsu", value:"Rocky", label:"Rocky"},
  {brand:"Daihatsu", value:"Sirion", label:"Sirion"},
  {brand:"Daihatsu", value:"Terios", label:"Terios"},
  {brand:"Dodge", value:"Avenger", label:"Avenger"},
  {brand:"Dodge", value:"Caliber", label:"Caliber"},
  {brand:"Dodge", value:"Caravan", label:"Caravan"},
  {brand:"Dodge", value:"Challenger", label:"Challenger"},
  {brand:"Dodge", value:"Charger", label:"Charger"},
  {brand:"Dodge", value:"Durango", label:"Durango"},
  {brand:"Dodge", value:"Grand Caravan", label:"Grand Caravan"},
  {brand:"Dodge", value:"Journey", label:"Journey"},
  {brand:"Dodge", value:"Kita", label:"Kita"},
  {brand:"Dodge", value:"Magnum", label:"Magnum"},
  {brand:"Dodge", value:"Neon", label:"Neon"},
  {brand:"Dodge", value:"Nitro", label:"Nitro"},
  {brand:"Dodge", value:"Operatyvioji atmintis (RAM)", label:"Operatyvioji atmintis (RAM)"},
  {brand:"Dodge", value:"Stratus", label:"Stratus"},
  {brand:"Dodge", value:"Viper", label:"Viper"},
  {brand:"Ferrari", value:"456", label:"456"},
  {brand:"Fiat", value:"", label:""},
  {brand:"Fiat", value:"500", label:"500"},
  {brand:"Fiat", value:"500 Abarth", label:"500 Abarth"},
  {brand:"Fiat", value:"500L", label:"500L"},
  {brand:"Fiat", value:"500X", label:"500X"},
  {brand:"Fiat", value:"Barchetta", label:"Barchetta"},
  {brand:"Fiat", value:"Brava", label:"Brava"},
  {brand:"Fiat", value:"Bravo", label:"Bravo"},
  {brand:"Fiat", value:"Croma", label:"Croma"},
  {brand:"Fiat", value:"Doblo", label:"Doblo"},
  {brand:"Fiat", value:"Ducato", label:"Ducato"},
  {brand:"Fiat", value:"Fiorino", label:"Fiorino"},
  {brand:"Fiat", value:"Freemont", label:"Freemont"},
  {brand:"Fiat", value:"Fullback", label:"Fullback"},
  {brand:"Fiat", value:"Grande Punto", label:"Grande Punto"},
  {brand:"Fiat", value:"Idea", label:"Idea"},
  {brand:"Fiat", value:"Kita", label:"Kita"},
  {brand:"Fiat", value:"Kupė (Coupe)", label:"Kupė (Coupe)"},
  {brand:"Fiat", value:"Linea", label:"Linea"},
  {brand:"Fiat", value:"Multipla", label:"Multipla"},
  {brand:"Fiat", value:"Panda", label:"Panda"},
  {brand:"Fiat", value:"Punto", label:"Punto"},
  {brand:"Fiat", value:"Punto Evo", label:"Punto Evo"},
  {brand:"Fiat", value:"Scudo", label:"Scudo"},
  {brand:"Fiat", value:"Sedici", label:"Sedici"},
  {brand:"Fiat", value:"Stilo", label:"Stilo"},
  {brand:"Fiat", value:"Tipo", label:"Tipo"},
  {brand:"Fiat", value:"Ulysse", label:"Ulysse"},
  {brand:"Ford", value:"B-MAX", label:"B-MAX"},
  {brand:"Ford", value:"C-MAX", label:"C-MAX"},
  {brand:"Ford", value:"Connect Tourneo", label:"Connect Tourneo"},
  {brand:"Ford", value:"Cougar", label:"Cougar"},
  {brand:"Ford", value:"Econoline", label:"Econoline"},
  {brand:"Ford", value:"EcoSport", label:"EcoSport"},
  {brand:"Ford", value:"Edge", label:"Edge"},
  {brand:"Ford", value:"Escape", label:"Escape"},
  {brand:"Ford", value:"Escort", label:"Escort"},
  {brand:"Ford", value:"Expedition", label:"Expedition"},
  {brand:"Ford", value:"Explorer", label:"Explorer"},
  {brand:"Ford", value:"F150", label:"F150"},
  {brand:"Ford", value:"F250", label:"F250"},
  {brand:"Ford", value:"F350", label:"F350"},
  {brand:"Ford", value:"Fiesta", label:"Fiesta"},
  {brand:"Ford", value:"Focus", label:"Focus"},
  {brand:"Ford", value:"Fusion", label:"Fusion"},
  {brand:"Ford", value:"Galaxy", label:"Galaxy"},
  {brand:"Ford", value:"Granada", label:"Granada"},
  {brand:"Ford", value:"Grand C-MAX", label:"Grand C-MAX"},
  {brand:"Ford", value:"GT", label:"GT"},
  {brand:"Ford", value:"Ka", label:"Ka"},
  {brand:"Ford", value:"Kita", label:"Kita"},
  {brand:"Ford", value:"Kuga", label:"Kuga"},
  {brand:"Ford", value:"Maverick", label:"Maverick"},
  {brand:"Ford", value:"Mercury", label:"Mercury"},
  {brand:"Ford", value:"Mondeo", label:"Mondeo"},
  {brand:"Ford", value:"Mustang", label:"Mustang"},
  {brand:"Ford", value:"pažintinės ekskursijos", label:"pažintinės ekskursijos"},
  {brand:"Ford", value:"Probe", label:"Probe"},
  {brand:"Ford", value:"Puma", label:"Puma"},
  {brand:"Ford", value:"Ranger", label:"Ranger"},
  {brand:"Ford", value:"Scorpio", label:"Scorpio"},
  {brand:"Ford", value:"S-MAX", label:"S-MAX"},
  {brand:"Ford", value:"Taunus", label:"Taunus"},
  {brand:"Ford", value:"Thunderbird", label:"Thunderbird"},
  {brand:"Ford", value:"Tourneo", label:"Tourneo"},
  {brand:"Ford", value:"Transit", label:"Transit"},
  {brand:"Ford", value:"Transit Connect", label:"Transit Connect"},
  {brand:"Ford", value:"Transit Custom", label:"Transit Custom"},
  {brand:"Ford", value:"Windstar", label:"Windstar"},
  {brand:"GAZ", value:"12 ZiM", label:"12 ZiM"},
  {brand:"GAZ", value:"21", label:"21"},
  {brand:"GAZ", value:"24", label:"24"},
  {brand:"GAZ", value:"2410", label:"2410"},
  {brand:"GAZ", value:"3110", label:"3110"},
  {brand:"GAZ", value:"32213", label:"32213"},
  {brand:"GAZ", value:"67", label:"67"},
  {brand:"GAZ", value:"69A", label:"69A"},
  {brand:"GAZ", value:"Kita", label:"Kita"},
  {brand:"GAZ", value:"M-20 Pobeda", label:"M-20 Pobeda"},
  {brand:"GAZ", value:"Volga", label:"Volga"},
  {brand:"GMC", value:"Priemiestinis", label:"Priemiestinis"},
  {brand:"GMC", value:"Savana", label:"Savana"},
  {brand:"GMC", value:"Sierra", label:"Sierra"},
  {brand:"GMC", value:"Terrain", label:"Terrain"},
  {brand:"GMC", value:"Yukon", label:"Yukon"},
  {brand:"Great Wall", value:"Hover", label:"Hover"},
  {brand:"Honda", value:"Accord", label:"Accord"},
  {brand:"Honda", value:"Civic", label:"Civic"},
  {brand:"Honda", value:"Crosstour", label:"Crosstour"},
  {brand:"Honda", value:"CR-V", label:"CR-V"},
  {brand:"Honda", value:"CRX", label:"CRX"},
  {brand:"Honda", value:"CRZ", label:"CRZ"},
  {brand:"Honda", value:"FIT", label:"FIT"},
  {brand:"Honda", value:"FR-V", label:"FR-V"},
  {brand:"Honda", value:"HR-V", label:"HR-V"},
  {brand:"Honda", value:"Insight", label:"Insight"},
  {brand:"Honda", value:"Integra", label:"Integra"},
  {brand:"Honda", value:"Jazz", label:"Jazz"},
  {brand:"Honda", value:"Legend", label:"Legend"},
  {brand:"Honda", value:"logotipas", label:"logotipas"},
  {brand:"Honda", value:"Odyssey", label:"Odyssey"},
  {brand:"Honda", value:"Pilot", label:"Pilot"},
  {brand:"Honda", value:"Prelude", label:"Prelude"},
  {brand:"Honda", value:"Ridgeline", label:"Ridgeline"},
  {brand:"Honda", value:"S2000", label:"S2000"},
  {brand:"Honda", value:"Shuttle", label:"Shuttle"},
  {brand:"Honda", value:"Stream", label:"Stream"},
  {brand:"Hummer", value:"H2", label:"H2"},
  {brand:"Hummer", value:"H3", label:"H3"},
  {brand:"Hyundai", value:"Accent", label:"Accent"},
  {brand:"Hyundai", value:"Atos", label:"Atos"},
  {brand:"Hyundai", value:"Elantra", label:"Elantra"},
  {brand:"Hyundai", value:"Galloper", label:"Galloper"},
  {brand:"Hyundai", value:"Genesis", label:"Genesis"},
  {brand:"Hyundai", value:"Getz", label:"Getz"},
  {brand:"Hyundai", value:"Grandeur", label:"Grandeur"},
  {brand:"Hyundai", value:"H1", label:"H1"},
  {brand:"Hyundai", value:"i10", label:"i10"},
  {brand:"Hyundai", value:"i20", label:"i20"},
  {brand:"Hyundai", value:"i30", label:"i30"},
  {brand:"Hyundai", value:"i40", label:"i40"},
  {brand:"Hyundai", value:"IONIQ", label:"IONIQ"},
  {brand:"Hyundai", value:"ix20", label:"ix20"},
  {brand:"Hyundai", value:"ix35", label:"ix35"},
  {brand:"Hyundai", value:"ix55", label:"ix55"},
  {brand:"Hyundai", value:"Kupė (Coupe)", label:"Kupė (Coupe)"},
  {brand:"Hyundai", value:"Matrix", label:"Matrix"},
  {brand:"Hyundai", value:"Santa Fė", label:"Santa Fė"},
  {brand:"Hyundai", value:"Sonata", label:"Sonata"},
  {brand:"Hyundai", value:"Starex", label:"Starex"},
  {brand:"Hyundai", value:"Terracan", label:"Terracan"},
  {brand:"Hyundai", value:"Trajet", label:"Trajet"},
  {brand:"Hyundai", value:"Tucson", label:"Tucson"},
  {brand:"Hyundai", value:"Veloster", label:"Veloster"},
  {brand:"Hyundai", value:"XG", label:"XG"},
  {brand:"Infiniti", value:"EX35", label:"EX35"},
  {brand:"Infiniti", value:"EX37", label:"EX37"},
  {brand:"Infiniti", value:"FX30", label:"FX30"},
  {brand:"Infiniti", value:"FX35", label:"FX35"},
  {brand:"Infiniti", value:"FX37", label:"FX37"},
  {brand:"Infiniti", value:"FX45", label:"FX45"},
  {brand:"Infiniti", value:"FX50", label:"FX50"},
  {brand:"Infiniti", value:"G35", label:"G35"},
  {brand:"Infiniti", value:"G37", label:"G37"},
  {brand:"Infiniti", value:"I35", label:"I35"},
  {brand:"Infiniti", value:"JX35", label:"JX35"},
  {brand:"Infiniti", value:"M30", label:"M30"},
  {brand:"Infiniti", value:"QX50", label:"QX50"},
  {brand:"Infiniti", value:"QX56", label:"QX56"},
  {brand:"Infiniti", value:"QX70", label:"QX70"},
  {brand:"Isuzu", value:"Axiom", label:"Axiom"},
  {brand:"Isuzu", value:"D-Max", label:"D-Max"},
  {brand:"Isuzu", value:"Rodeo", label:"Rodeo"},
  {brand:"Isuzu", value:"Trooper", label:"Trooper"},
  {brand:"Isuzu", value:"Vehi Cross", label:"Vehi Cross"},
  {brand:"Iveco", value:"Daily", label:"Daily"},
  {brand:"Jaguar", value:"F-Pace", label:"F-Pace"},
  {brand:"Jaguar", value:"Kita", label:"Kita"},
  {brand:"Jaguar", value:"Sovereign", label:"Sovereign"},
  {brand:"Jaguar", value:"S-Type", label:"S-Type"},
  {brand:"Jaguar", value:"XE", label:"XE"},
  {brand:"Jaguar", value:"XF", label:"XF"},
  {brand:"Jaguar", value:"XJ", label:"XJ"},
  {brand:"Jaguar", value:"XJ12", label:"XJ12"},
  {brand:"Jaguar", value:"XJ6", label:"XJ6"},
  {brand:"Jaguar", value:"XJ8", label:"XJ8"},
  {brand:"Jaguar", value:"XJR", label:"XJR"},
  {brand:"Jaguar", value:"XJS", label:"XJS"},
  {brand:"Jaguar", value:"XJ-Series", label:"XJ-Series"},
  {brand:"Jaguar", value:"XK", label:"XK"},
  {brand:"Jaguar", value:"XKR", label:"XKR"},
  {brand:"Jaguar", value:"X-Type", label:"X-Type"},
  {brand:"Jeep", value:"Cherokee", label:"Cherokee"},
  {brand:"Jeep", value:"Commander", label:"Commander"},
  {brand:"Jeep", value:"Compass", label:"Compass"},
  {brand:"Jeep", value:"Grand Cherokee", label:"Grand Cherokee"},
  {brand:"Jeep", value:"Liberty", label:"Liberty"},
  {brand:"Jeep", value:"Patriot", label:"Patriot"},
  {brand:"Jeep", value:"Renegade", label:"Renegade"},
  {brand:"Jeep", value:"Wrangler", label:"Wrangler"},
  {brand:"Kia", value:"Carens", label:"Carens"},
  {brand:"Kia", value:"Carnival", label:"Carnival"},
  {brand:"Kia", value:"Cee'd", label:"Cee'd"},
  {brand:"Kia", value:"Cerato", label:"Cerato"},
  {brand:"Kia", value:"Kita", label:"Kita"},
  {brand:"Kia", value:"Magentis", label:"Magentis"},
  {brand:"Kia", value:"Niro", label:"Niro"},
  {brand:"Kia", value:"Opirus", label:"Opirus"},
  {brand:"Kia", value:"Optima", label:"Optima"},
  {brand:"Kia", value:"Picanto", label:"Picanto"},
  {brand:"Kia", value:"Pro cee'd", label:"Pro cee'd"},
  {brand:"Kia", value:"Retona", label:"Retona"},
  {brand:"Kia", value:"Rio", label:"Rio"},
  {brand:"Kia", value:"Sorento", label:"Sorento"},
  {brand:"Kia", value:"Soul", label:"Soul"},
  {brand:"Kia", value:"Sportage", label:"Sportage"},
  {brand:"Kia", value:"Venga", label:"Venga"},
  {brand:"Kita", value:"Kita", label:"Kita"},
  {brand:"Lada", value:"2101", label:"2101"},
  {brand:"Lada", value:"21011", label:"21011"},
  {brand:"Lada", value:"2102", label:"2102"},
  {brand:"Lada", value:"2103", label:"2103"},
  {brand:"Lada", value:"2104", label:"2104"},
  {brand:"Lada", value:"2105", label:"2105"},
  {brand:"Lada", value:"21051", label:"21051"},
  {brand:"Lada", value:"2106", label:"2106"},
  {brand:"Lada", value:"21061", label:"21061"},
  {brand:"Lada", value:"2107", label:"2107"},
  {brand:"Lada", value:"2108", label:"2108"},
  {brand:"Lada", value:"2109", label:"2109"},
  {brand:"Lada", value:"21214", label:"21214"},
  {brand:"Lada", value:"Niva", label:"Niva"},
  {brand:"Lancia", value:"Delta", label:"Delta"},
  {brand:"Lancia", value:"Kappa", label:"Kappa"},
  {brand:"Lancia", value:"Lybra", label:"Lybra"},
  {brand:"Lancia", value:"Musa", label:"Musa"},
  {brand:"Lancia", value:"Phedra", label:"Phedra"},
  {brand:"Lancia", value:"Thema", label:"Thema"},
  {brand:"Lancia", value:"Thesis", label:"Thesis"},
  {brand:"Lancia", value:"Ypsilon", label:"Ypsilon"},
  {brand:"Land Rover", value:"Defender", label:"Defender"},
  {brand:"Land Rover", value:"Discovery", label:"Discovery"},
  {brand:"Land Rover", value:"Evoque", label:"Evoque"},
  {brand:"Land Rover", value:"Freelander", label:"Freelander"},
  {brand:"Land Rover", value:"Range Rover", label:"Range Rover"},
  {brand:"Land Rover", value:"Range Rover Sport", label:"Range Rover Sport"},
  {brand:"Lexus", value:"", label:""},
  {brand:"Lexus", value:"CT 200h", label:"CT 200h"},
  {brand:"Lexus", value:"ES 300", label:"ES 300"},
  {brand:"Lexus", value:"ES 350", label:"ES 350"},
  {brand:"Lexus", value:"GS 200t", label:"GS 200t"},
  {brand:"Lexus", value:"GS 250", label:"GS 250"},
  {brand:"Lexus", value:"GS 300", label:"GS 300"},
  {brand:"Lexus", value:"GS 300h", label:"GS 300h"},
  {brand:"Lexus", value:"GS 350 ", label:"GS 350 "},
  {brand:"Lexus", value:"GS 430", label:"GS 430"},
  {brand:"Lexus", value:"GS 450", label:"GS 450"},
  {brand:"Lexus", value:"GX 460", label:"GX 460"},
  {brand:"Lexus", value:"GX 470", label:"GX 470"},
  {brand:"Lexus", value:"HS 250", label:"HS 250"},
  {brand:"Lexus", value:"IS 200", label:"IS 200"},
  {brand:"Lexus", value:"IS 220", label:"IS 220"},
  {brand:"Lexus", value:"IS 250", label:"IS 250"},
  {brand:"Lexus", value:"IS 300", label:"IS 300"},
  {brand:"Lexus", value:"IS 300h", label:"IS 300h"},
  {brand:"Lexus", value:"IS 350", label:"IS 350"},
  {brand:"Lexus", value:"IS-F", label:"IS-F"},
  {brand:"Lexus", value:"LS 400", label:"LS 400"},
  {brand:"Lexus", value:"LS 430", label:"LS 430"},
  {brand:"Lexus", value:"LS 460", label:"LS 460"},
  {brand:"Lexus", value:"LS 600 h", label:"LS 600 h"},
  {brand:"Lexus", value:"LX 470", label:"LX 470"},
  {brand:"Lexus", value:"LX 570", label:"LX 570"},
  {brand:"Lexus", value:"NX 200t", label:"NX 200t"},
  {brand:"Lexus", value:"NX 300h", label:"NX 300h"},
  {brand:"Lexus", value:"RC 200t", label:"RC 200t"},
  {brand:"Lexus", value:"RC 350", label:"RC 350"},
  {brand:"Lexus", value:"RX 300", label:"RX 300"},
  {brand:"Lexus", value:"RX 330", label:"RX 330"},
  {brand:"Lexus", value:"RX 350", label:"RX 350"},
  {brand:"Lexus", value:"RX 400h", label:"RX 400h"},
  {brand:"Lexus", value:"RX 450h", label:"RX 450h"},
  {brand:"Lexus", value:"SC 400", label:"SC 400"},
  {brand:"Lexus", value:"SC 430", label:"SC 430"},
  {brand:"Ligier", value:"ixo", label:"ixo"},
  {brand:"Ligier", value:"Kita", label:"Kita"},
  {brand:"Ligier", value:"X - Too", label:"X - Too"},
  {brand:"Lincoln", value:"Continental", label:"Continental"},
  {brand:"Lincoln", value:"Kita", label:"Kita"},
  {brand:"Lincoln", value:"LS", label:"LS"},
  {brand:"Lincoln", value:"MKZ", label:"MKZ"},
  {brand:"Lincoln", value:"Navigator", label:"Navigator"},
  {brand:"Lincoln", value:"Town Car", label:"Town Car"},
  {brand:"LuAZ", value:"969M", label:"969M"},
  {brand:"Maserati", value:"3200 GT", label:"3200 GT"},
  {brand:"Maserati", value:"Ghibli", label:"Ghibli"},
  {brand:"Maserati", value:"GranTurismo", label:"GranTurismo"},
  {brand:"Maserati", value:"Quattroporte", label:"Quattroporte"},
  {brand:"Mazda", value:"2", label:"2"},
  {brand:"Mazda", value:"3", label:"3"},
  {brand:"Mazda", value:"323", label:"323"},
  {brand:"Mazda", value:"323F", label:"323F"},
  {brand:"Mazda", value:"5", label:"5"},
  {brand:"Mazda", value:"6", label:"6"},
  {brand:"Mazda", value:"626", label:"626"},
  {brand:"Mazda", value:"929", label:"929"},
  {brand:"Mazda", value:"B Series", label:"B Series"},
  {brand:"Mazda", value:"BT-50", label:"BT-50"},
  {brand:"Mazda", value:"CX-3", label:"CX-3"},
  {brand:"Mazda", value:"CX-5", label:"CX-5"},
  {brand:"Mazda", value:"CX-7", label:"CX-7"},
  {brand:"Mazda", value:"CX-9", label:"CX-9"},
  {brand:"Mazda", value:"Demio", label:"Demio"},
  {brand:"Mazda", value:"Kita", label:"Kita"},
  {brand:"Mazda", value:"Millenia", label:"Millenia"},
  {brand:"Mazda", value:"MPV", label:"MPV"},
  {brand:"Mazda", value:"MX-3", label:"MX-3"},
  {brand:"Mazda", value:"MX-5", label:"MX-5"},
  {brand:"Mazda", value:"Premacy", label:"Premacy"},
  {brand:"Mazda", value:"Protege", label:"Protege"},
  {brand:"Mazda", value:"RX-8", label:"RX-8"},
  {brand:"Mazda", value:"Tribute", label:"Tribute"},
  {brand:"Mercedes-Benz", value:"123", label:"123"},
  {brand:"Mercedes-Benz", value:"124", label:"124"},
  {brand:"Mercedes-Benz", value:"190", label:"190"},
  {brand:"Mercedes-Benz", value:"200", label:"200"},
  {brand:"Mercedes-Benz", value:"207", label:"207"},
  {brand:"Mercedes-Benz", value:"208", label:"208"},
  {brand:"Mercedes-Benz", value:"211", label:"211"},
  {brand:"Mercedes-Benz", value:"220", label:"220"},
  {brand:"Mercedes-Benz", value:"230", label:"230"},
  {brand:"Mercedes-Benz", value:"240", label:"240"},
  {brand:"Mercedes-Benz", value:"250", label:"250"},
  {brand:"Mercedes-Benz", value:"260", label:"260"},
  {brand:"Mercedes-Benz", value:"280", label:"280"},
  {brand:"Mercedes-Benz", value:"290", label:"290"},
  {brand:"Mercedes-Benz", value:"300", label:"300"},
  {brand:"Mercedes-Benz", value:"320", label:"320"},
  {brand:"Mercedes-Benz", value:"A140", label:"A140"},
  {brand:"Mercedes-Benz", value:"A150", label:"A150"},
  {brand:"Mercedes-Benz", value:"A160", label:"A160"},
  {brand:"Mercedes-Benz", value:"A170", label:"A170"},
  {brand:"Mercedes-Benz", value:"A180", label:"A180"},
  {brand:"Mercedes-Benz", value:"A190", label:"A190"},
  {brand:"Mercedes-Benz", value:"A200", label:"A200"},
  {brand:"Mercedes-Benz", value:"A250", label:"A250"},
  {brand:"Mercedes-Benz", value:"B150", label:"B150"},
  {brand:"Mercedes-Benz", value:"B160", label:"B160"},
  {brand:"Mercedes-Benz", value:"B170", label:"B170"},
  {brand:"Mercedes-Benz", value:"B180", label:"B180"},
  {brand:"Mercedes-Benz", value:"B200", label:"B200"},
  {brand:"Mercedes-Benz", value:"B220", label:"B220"},
  {brand:"Mercedes-Benz", value:"C klasė SC", label:"C klasė SC"},
  {brand:"Mercedes-Benz", value:"C180", label:"C180"},
  {brand:"Mercedes-Benz", value:"C200", label:"C200"},
  {brand:"Mercedes-Benz", value:"C220", label:"C220"},
  {brand:"Mercedes-Benz", value:"C230", label:"C230"},
  {brand:"Mercedes-Benz", value:"C240", label:"C240"},
  {brand:"Mercedes-Benz", value:"C250", label:"C250"},
  {brand:"Mercedes-Benz", value:"C270", label:"C270"},
  {brand:"Mercedes-Benz", value:"C280", label:"C280"},
  {brand:"Mercedes-Benz", value:"C30 AMG", label:"C30 AMG"},
  {brand:"Mercedes-Benz", value:"C300", label:"C300"},
  {brand:"Mercedes-Benz", value:"C32 AMG", label:"C32 AMG"},
  {brand:"Mercedes-Benz", value:"C320", label:"C320"},
  {brand:"Mercedes-Benz", value:"C350", label:"C350"},
  {brand:"Mercedes-Benz", value:"C400", label:"C400"},
  {brand:"Mercedes-Benz", value:"C43 AMG", label:"C43 AMG"},
  {brand:"Mercedes-Benz", value:"C450", label:"C450"},
  {brand:"Mercedes-Benz", value:"C63 AMG", label:"C63 AMG"},
  {brand:"Mercedes-Benz", value:"CE230", label:"CE230"},
  {brand:"Mercedes-Benz", value:"CE300", label:"CE300"},
  {brand:"Mercedes-Benz", value:"Citan", label:"Citan"},
  {brand:"Mercedes-Benz", value:"CL200", label:"CL200"},
  {brand:"Mercedes-Benz", value:"CL420", label:"CL420"},
  {brand:"Mercedes-Benz", value:"CL500", label:"CL500"},
  {brand:"Mercedes-Benz", value:"CL55 AMG", label:"CL55 AMG"},
  {brand:"Mercedes-Benz", value:"CL600", label:"CL600"},
  {brand:"Mercedes-Benz", value:"CL63 AMG", label:"CL63 AMG"},
  {brand:"Mercedes-Benz", value:"CLA180", label:"CLA180"},
  {brand:"Mercedes-Benz", value:"CLA200", label:"CLA200"},
  {brand:"Mercedes-Benz", value:"CLA220", label:"CLA220"},
  {brand:"Mercedes-Benz", value:"CLA250", label:"CLA250"},
  {brand:"Mercedes-Benz", value:"CLA45 AMG", label:"CLA45 AMG"},
  {brand:"Mercedes-Benz", value:"CLC200", label:"CLC200"},
  {brand:"Mercedes-Benz", value:"CLC220", label:"CLC220"},
  {brand:"Mercedes-Benz", value:"CLC230", label:"CLC230"},
  {brand:"Mercedes-Benz", value:"CLK200", label:"CLK200"},
  {brand:"Mercedes-Benz", value:"CLK220", label:"CLK220"},
  {brand:"Mercedes-Benz", value:"CLK230", label:"CLK230"},
  {brand:"Mercedes-Benz", value:"CLK240", label:"CLK240"},
  {brand:"Mercedes-Benz", value:"CLK270", label:"CLK270"},
  {brand:"Mercedes-Benz", value:"CLK320", label:"CLK320"},
  {brand:"Mercedes-Benz", value:"CLK350", label:"CLK350"},
  {brand:"Mercedes-Benz", value:"CLK500", label:"CLK500"},
  {brand:"Mercedes-Benz", value:"CLK55 AMG", label:"CLK55 AMG"},
  {brand:"Mercedes-Benz", value:"CLS280", label:"CLS280"},
  {brand:"Mercedes-Benz", value:"CLS300", label:"CLS300"},
  {brand:"Mercedes-Benz", value:"CLS320", label:"CLS320"},
  {brand:"Mercedes-Benz", value:"CLS350", label:"CLS350"},
  {brand:"Mercedes-Benz", value:"CLS500", label:"CLS500"},
  {brand:"Mercedes-Benz", value:"CLS55 AMG", label:"CLS55 AMG"},
  {brand:"Mercedes-Benz", value:"CLS550", label:"CLS550"},
  {brand:"Mercedes-Benz", value:"CLS63 AMG", label:"CLS63 AMG"},
  {brand:"Mercedes-Benz", value:"E klasė", label:"E klasė"},
  {brand:"Mercedes-Benz", value:"E200", label:"E200"},
  {brand:"Mercedes-Benz", value:"E220", label:"E220"},
  {brand:"Mercedes-Benz", value:"E230", label:"E230"},
  {brand:"Mercedes-Benz", value:"E240", label:"E240"},
  {brand:"Mercedes-Benz", value:"E250", label:"E250"},
  {brand:"Mercedes-Benz", value:"E270", label:"E270"},
  {brand:"Mercedes-Benz", value:"E280", label:"E280"},
  {brand:"Mercedes-Benz", value:"E290", label:"E290"},
  {brand:"Mercedes-Benz", value:"E300", label:"E300"},
  {brand:"Mercedes-Benz", value:"E320", label:"E320"},
  {brand:"Mercedes-Benz", value:"E350", label:"E350"},
  {brand:"Mercedes-Benz", value:"E400", label:"E400"},
  {brand:"Mercedes-Benz", value:"E420", label:"E420"},
  {brand:"Mercedes-Benz", value:"E430", label:"E430"},
  {brand:"Mercedes-Benz", value:"E500", label:"E500"},
  {brand:"Mercedes-Benz", value:"E55 AMG", label:"E55 AMG"},
  {brand:"Mercedes-Benz", value:"E63 AMG", label:"E63 AMG"},
  {brand:"Mercedes-Benz", value:"G230", label:"G230"},
  {brand:"Mercedes-Benz", value:"G240", label:"G240"},
  {brand:"Mercedes-Benz", value:"G270", label:"G270"},
  {brand:"Mercedes-Benz", value:"G300", label:"G300"},
  {brand:"Mercedes-Benz", value:"G350", label:"G350"},
  {brand:"Mercedes-Benz", value:"G400", label:"G400"},
  {brand:"Mercedes-Benz", value:"G55 AMG", label:"G55 AMG"},
  {brand:"Mercedes-Benz", value:"GL320", label:"GL320"},
  {brand:"Mercedes-Benz", value:"GL350", label:"GL350"},
  {brand:"Mercedes-Benz", value:"GL350 BlueTEC", label:"GL350 BlueTEC"},
  {brand:"Mercedes-Benz", value:"GL420", label:"GL420"},
  {brand:"Mercedes-Benz", value:"GL450", label:"GL450"},
  {brand:"Mercedes-Benz", value:"GL500", label:"GL500"},
  {brand:"Mercedes-Benz", value:"GL550", label:"GL550"},
  {brand:"Mercedes-Benz", value:"GL63 AMG", label:"GL63 AMG"},
  {brand:"Mercedes-Benz", value:"GLA180", label:"GLA180"},
  {brand:"Mercedes-Benz", value:"GLA200", label:"GLA200"},
  {brand:"Mercedes-Benz", value:"GLA250", label:"GLA250"},
  {brand:"Mercedes-Benz", value:"GLC Coupe 220 ", label:"GLC Coupe 220 "},
  {brand:"Mercedes-Benz", value:"GLC220", label:"GLC220"},
  {brand:"Mercedes-Benz", value:"GLC250", label:"GLC250"},
  {brand:"Mercedes-Benz", value:"GLC300", label:"GLC300"},
  {brand:"Mercedes-Benz", value:"GLE Coupe 250", label:"GLE Coupe 250"},
  {brand:"Mercedes-Benz", value:"GLE Coupe 63 AMG", label:"GLE Coupe 63 AMG"},
  {brand:"Mercedes-Benz", value:"GLE350", label:"GLE350"},
  {brand:"Mercedes-Benz", value:"GLE400", label:"GLE400"},
  {brand:"Mercedes-Benz", value:"GLK200", label:"GLK200"},
  {brand:"Mercedes-Benz", value:"GLK220", label:"GLK220"},
  {brand:"Mercedes-Benz", value:"GLK250", label:"GLK250"},
  {brand:"Mercedes-Benz", value:"GLK300", label:"GLK300"},
  {brand:"Mercedes-Benz", value:"GLK320", label:"GLK320"},
  {brand:"Mercedes-Benz", value:"GLK350", label:"GLK350"},
  {brand:"Mercedes-Benz", value:"Kita", label:"Kita"},
  {brand:"Mercedes-Benz", value:"ML230", label:"ML230"},
  {brand:"Mercedes-Benz", value:"ML250", label:"ML250"},
  {brand:"Mercedes-Benz", value:"ML270", label:"ML270"},
  {brand:"Mercedes-Benz", value:"ML280", label:"ML280"},
  {brand:"Mercedes-Benz", value:"ML300", label:"ML300"},
  {brand:"Mercedes-Benz", value:"ML320", label:"ML320"},
  {brand:"Mercedes-Benz", value:"ML350", label:"ML350"},
  {brand:"Mercedes-Benz", value:"ML400", label:"ML400"},
  {brand:"Mercedes-Benz", value:"ML420", label:"ML420"},
  {brand:"Mercedes-Benz", value:"ML430", label:"ML430"},
  {brand:"Mercedes-Benz", value:"ML450", label:"ML450"},
  {brand:"Mercedes-Benz", value:"ML500", label:"ML500"},
  {brand:"Mercedes-Benz", value:"ML55 AMG", label:"ML55 AMG"},
  {brand:"Mercedes-Benz", value:"ML63 AMG", label:"ML63 AMG"},
  {brand:"Mercedes-Benz", value:"R280", label:"R280"},
  {brand:"Mercedes-Benz", value:"R300", label:"R300"},
  {brand:"Mercedes-Benz", value:"R320", label:"R320"},
  {brand:"Mercedes-Benz", value:"R350", label:"R350"},
  {brand:"Mercedes-Benz", value:"R500", label:"R500"},
  {brand:"Mercedes-Benz", value:"S250", label:"S250"},
  {brand:"Mercedes-Benz", value:"S260", label:"S260"},
  {brand:"Mercedes-Benz", value:"S280", label:"S280"},
  {brand:"Mercedes-Benz", value:"S300", label:"S300"},
  {brand:"Mercedes-Benz", value:"S320", label:"S320"},
  {brand:"Mercedes-Benz", value:"S350", label:"S350"},
  {brand:"Mercedes-Benz", value:"S400", label:"S400"},
  {brand:"Mercedes-Benz", value:"S420", label:"S420"},
  {brand:"Mercedes-Benz", value:"S430", label:"S430"},
  {brand:"Mercedes-Benz", value:"S450", label:"S450"},
  {brand:"Mercedes-Benz", value:"S500", label:"S500"},
  {brand:"Mercedes-Benz", value:"S55 AMG", label:"S55 AMG"},
  {brand:"Mercedes-Benz", value:"S550", label:"S550"},
  {brand:"Mercedes-Benz", value:"S600", label:"S600"},
  {brand:"Mercedes-Benz", value:"S63 AMG", label:"S63 AMG"},
  {brand:"Mercedes-Benz", value:"SL280", label:"SL280"},
  {brand:"Mercedes-Benz", value:"SL350", label:"SL350"},
  {brand:"Mercedes-Benz", value:"SL380", label:"SL380"},
  {brand:"Mercedes-Benz", value:"SL450", label:"SL450"},
  {brand:"Mercedes-Benz", value:"SL500", label:"SL500"},
  {brand:"Mercedes-Benz", value:"SL55 AMG", label:"SL55 AMG"},
  {brand:"Mercedes-Benz", value:"SL65 AMG", label:"SL65 AMG"},
  {brand:"Mercedes-Benz", value:"SLK200", label:"SLK200"},
  {brand:"Mercedes-Benz", value:"SLK230", label:"SLK230"},
  {brand:"Mercedes-Benz", value:"SLK280 ", label:"SLK280 "},
  {brand:"Mercedes-Benz", value:"SLK300", label:"SLK300"},
  {brand:"Mercedes-Benz", value:"SLK320", label:"SLK320"},
  {brand:"Mercedes-Benz", value:"SLK350", label:"SLK350"},
  {brand:"Mercedes-Benz", value:"SLK55 AMG", label:"SLK55 AMG"},
  {brand:"Mercedes-Benz", value:"Sprinter", label:"Sprinter"},
  {brand:"Mercedes-Benz", value:"V200", label:"V200"},
  {brand:"Mercedes-Benz", value:"V220", label:"V220"},
  {brand:"Mercedes-Benz", value:"V230", label:"V230"},
  {brand:"Mercedes-Benz", value:"V250", label:"V250"},
  {brand:"Mercedes-Benz", value:"V280", label:"V280"},
  {brand:"Mercedes-Benz", value:"Vaneo", label:"Vaneo"},
  {brand:"Mercedes-Benz", value:"Vario", label:"Vario"},
  {brand:"Mercedes-Benz", value:"Viano", label:"Viano"},
  {brand:"Mercedes-Benz", value:"Vito", label:"Vito"},
  {brand:"Mercury", value:"Cougar", label:"Cougar"},
  {brand:"Mercury", value:"Grand Marquis", label:"Grand Marquis"},
  {brand:"MG", value:"MGF", label:"MGF"},
  {brand:"MG", value:"ZR", label:"ZR"},
  {brand:"Microcar", value:"Kita", label:"Kita"},
  {brand:"Microcar", value:"Mgo", label:"Mgo"},
  {brand:"Mini", value:"Clubman", label:"Clubman"},
  {brand:"Mini", value:"Cooper", label:"Cooper"},
  {brand:"Mini", value:"Cooper S", label:"Cooper S"},
  {brand:"Mini", value:"Countryman", label:"Countryman"},
  {brand:"Mini", value:"Kita", label:"Kita"},
  {brand:"Mini", value:"Mini", label:"Mini"},
  {brand:"Mini", value:"One", label:"One"},
  {brand:"Mini", value:"Paceman", label:"Paceman"},
  {brand:"Mitsubishi", value:"3000 GT", label:"3000 GT"},
  {brand:"Mitsubishi", value:"ASX", label:"ASX"},
  {brand:"Mitsubishi", value:"Carisma", label:"Carisma"},
  {brand:"Mitsubishi", value:"Colt", label:"Colt"},
  {brand:"Mitsubishi", value:"Delica", label:"Delica"},
  {brand:"Mitsubishi", value:"Eclipse", label:"Eclipse"},
  {brand:"Mitsubishi", value:"Galant", label:"Galant"},
  {brand:"Mitsubishi", value:"Galloper", label:"Galloper"},
  {brand:"Mitsubishi", value:"Grandis", label:"Grandis"},
  {brand:"Mitsubishi", value:"L200", label:"L200"},
  {brand:"Mitsubishi", value:"L300", label:"L300"},
  {brand:"Mitsubishi", value:"L400", label:"L400"},
  {brand:"Mitsubishi", value:"Lancer", label:"Lancer"},
  {brand:"Mitsubishi", value:"Lancer  Evolution", label:"Lancer  Evolution"},
  {brand:"Mitsubishi", value:"Montero", label:"Montero"},
  {brand:"Mitsubishi", value:"Outlander", label:"Outlander"},
  {brand:"Mitsubishi", value:"Pajero", label:"Pajero"},
  {brand:"Mitsubishi", value:"Pajero Pinin", label:"Pajero Pinin"},
  {brand:"Mitsubishi", value:"Pajero Sport", label:"Pajero Sport"},
  {brand:"Mitsubishi", value:"Shogun", label:"Shogun"},
  {brand:"Mitsubishi", value:"Space Gear", label:"Space Gear"},
  {brand:"Mitsubishi", value:"Space Runner", label:"Space Runner"},
  {brand:"Mitsubishi", value:"Space Star", label:"Space Star"},
  {brand:"Mitsubishi", value:"Space Wagon", label:"Space Wagon"},
  {brand:"Moskvich", value:"2140", label:"2140"},
  {brand:"Moskvich", value:"2141", label:"2141"},
  {brand:"Moskvich", value:"401", label:"401"},
  {brand:"Moskvich", value:"403", label:"403"},
  {brand:"Moskvich", value:"M-400", label:"M-400"},
  {brand:"Nissan", value:"200 SX", label:"200 SX"},
  {brand:"Nissan", value:"300 ZX", label:"300 ZX"},
  {brand:"Nissan", value:"350Z", label:"350Z"},
  {brand:"Nissan", value:"370Z", label:"370Z"},
  {brand:"Nissan", value:"Almera", label:"Almera"},
  {brand:"Nissan", value:"Almera Tino", label:"Almera Tino"},
  {brand:"Nissan", value:"Altima", label:"Altima"},
  {brand:"Nissan", value:"Armada", label:"Armada"},
  {brand:"Nissan", value:"Bluebird", label:"Bluebird"},
  {brand:"Nissan", value:"Cube", label:"Cube"},
  {brand:"Nissan", value:"Evalia", label:"Evalia"},
  {brand:"Nissan", value:"Interstar", label:"Interstar"},
  {brand:"Nissan", value:"Juke", label:"Juke"},
  {brand:"Nissan", value:"King Cab", label:"King Cab"},
  {brand:"Nissan", value:"Kita", label:"Kita"},
  {brand:"Nissan", value:"Leaf", label:"Leaf"},
  {brand:"Nissan", value:"Maxima", label:"Maxima"},
  {brand:"Nissan", value:"Micra", label:"Micra"},
  {brand:"Nissan", value:"Murano", label:"Murano"},
  {brand:"Nissan", value:"Navara", label:"Navara"},
  {brand:"Nissan", value:"Note", label:"Note"},
  {brand:"Nissan", value:"NP300", label:"NP300"},
  {brand:"Nissan", value:"NV200", label:"NV200"},
  {brand:"Nissan", value:"Pathfinder", label:"Pathfinder"},
  {brand:"Nissan", value:"Patrol", label:"Patrol"},
  {brand:"Nissan", value:"Pixo", label:"Pixo"},
  {brand:"Nissan", value:"Primastar", label:"Primastar"},
  {brand:"Nissan", value:"Primera", label:"Primera"},
  {brand:"Nissan", value:"Pulsar", label:"Pulsar"},
  {brand:"Nissan", value:"Qashqai", label:"Qashqai"},
  {brand:"Nissan", value:"Qashqai+2", label:"Qashqai+2"},
  {brand:"Nissan", value:"Quest", label:"Quest"},
  {brand:"Nissan", value:"Serena", label:"Serena"},
  {brand:"Nissan", value:"Sunny", label:"Sunny"},
  {brand:"Nissan", value:"Terrano", label:"Terrano"},
  {brand:"Nissan", value:"Tiida", label:"Tiida"},
  {brand:"Nissan", value:"Titan", label:"Titan"},
  {brand:"Nissan", value:"Versa", label:"Versa"},
  {brand:"Nissan", value:"X-Terra", label:"X-Terra"},
  {brand:"Nissan", value:"X-Trail", label:"X-Trail"},
  {brand:"Oldsmobile", value:"Delta 88", label:"Delta 88"},
  {brand:"Oldsmobile", value:"Kita", label:"Kita"},
  {brand:"Opel", value:"Adam", label:"Adam"},
  {brand:"Opel", value:"Agila", label:"Agila"},
  {brand:"Opel", value:"Ampera", label:"Ampera"},
  {brand:"Opel", value:"Antara", label:"Antara"},
  {brand:"Opel", value:"Astra", label:"Astra"},
  {brand:"Opel", value:"Calibra", label:"Calibra"},
  {brand:"Opel", value:"Campo", label:"Campo"},
  {brand:"Opel", value:"Combo", label:"Combo"},
  {brand:"Opel", value:"Corsa", label:"Corsa"},
  {brand:"Opel", value:"Frontera", label:"Frontera"},
  {brand:"Opel", value:"Insignia", label:"Insignia"},
  {brand:"Opel", value:"Karl", label:"Karl"},
  {brand:"Opel", value:"Kita", label:"Kita"},
  {brand:"Opel", value:"Manta", label:"Manta"},
  {brand:"Opel", value:"Meriva", label:"Meriva"},
  {brand:"Opel", value:"Mokka", label:"Mokka"},
  {brand:"Opel", value:"Monterey", label:"Monterey"},
  {brand:"Opel", value:"Movano", label:"Movano"},
  {brand:"Opel", value:"Omega", label:"Omega"},
  {brand:"Opel", value:"Rekord", label:"Rekord"},
  {brand:"Opel", value:"Signum", label:"Signum"},
  {brand:"Opel", value:"Sintra", label:"Sintra"},
  {brand:"Opel", value:"Tigra", label:"Tigra"},
  {brand:"Opel", value:"Vectra", label:"Vectra"},
  {brand:"Opel", value:"Vivaro", label:"Vivaro"},
  {brand:"Opel", value:"Zafira", label:"Zafira"},
  {brand:"Opel", value:"Zafira tourer", label:"Zafira tourer"},
  {brand:"Peugeot", value:"1007", label:"1007"},
  {brand:"Peugeot", value:"106", label:"106"},
  {brand:"Peugeot", value:"107", label:"107"},
  {brand:"Peugeot", value:"108", label:"108"},
  {brand:"Peugeot", value:"2008", label:"2008"},
  {brand:"Peugeot", value:"206", label:"206"},
  {brand:"Peugeot", value:"206+", label:"206+"},
  {brand:"Peugeot", value:"207", label:"207"},
  {brand:"Peugeot", value:"208", label:"208"},
  {brand:"Peugeot", value:"3008", label:"3008"},
  {brand:"Peugeot", value:"306", label:"306"},
  {brand:"Peugeot", value:"307", label:"307"},
  {brand:"Peugeot", value:"308", label:"308"},
  {brand:"Peugeot", value:"4007", label:"4007"},
  {brand:"Peugeot", value:"4008", label:"4008"},
  {brand:"Peugeot", value:"406", label:"406"},
  {brand:"Peugeot", value:"407", label:"407"},
  {brand:"Peugeot", value:"5008", label:"5008"},
  {brand:"Peugeot", value:"508", label:"508"},
  {brand:"Peugeot", value:"508 RXH", label:"508 RXH"},
  {brand:"Peugeot", value:"607", label:"607"},
  {brand:"Peugeot", value:"806", label:"806"},
  {brand:"Peugeot", value:"807", label:"807"},
  {brand:"Peugeot", value:"Bipper", label:"Bipper"},
  {brand:"Peugeot", value:"Boxer", label:"Boxer"},
  {brand:"Peugeot", value:"Expert", label:"Expert"},
  {brand:"Peugeot", value:"Partner", label:"Partner"},
  {brand:"Peugeot", value:"RCZ", label:"RCZ"},
  {brand:"Plymouth", value:"Kita", label:"Kita"},
  {brand:"Pontiac", value:"Bonneville", label:"Bonneville"},
  {brand:"Pontiac", value:"Firebird", label:"Firebird"},
  {brand:"Pontiac", value:"Trans Am", label:"Trans Am"},
  {brand:"Pontiac", value:"Trans Sport", label:"Trans Sport"},
  {brand:"Pontiac", value:"Vibe", label:"Vibe"},
  {brand:"Porsche", value:"356", label:"356"},
  {brand:"Porsche", value:"911", label:"911"},
  {brand:"Porsche", value:"914", label:"914"},
  {brand:"Porsche", value:"924", label:"924"},
  {brand:"Porsche", value:"928", label:"928"},
  {brand:"Porsche", value:"Boxster", label:"Boxster"},
  {brand:"Porsche", value:"Cayenne", label:"Cayenne"},
  {brand:"Porsche", value:"Cayman", label:"Cayman"},
  {brand:"Porsche", value:"Macan", label:"Macan"},
  {brand:"Porsche", value:"Panamera", label:"Panamera"},
  {brand:"Proton", value:"Kita", label:"Kita"},
  {brand:"Renault", value:"11", label:"11"},
  {brand:"Renault", value:"19", label:"19"},
  {brand:"Renault", value:"Captur", label:"Captur"},
  {brand:"Renault", value:"Clio", label:"Clio"},
  {brand:"Renault", value:"Espace", label:"Espace"},
  {brand:"Renault", value:"Fluence", label:"Fluence"},
  {brand:"Renault", value:"Grand Espace", label:"Grand Espace"},
  {brand:"Renault", value:"Grand Scenic", label:"Grand Scenic"},
  {brand:"Renault", value:"Kadjar", label:"Kadjar"},
  {brand:"Renault", value:"Kangoo", label:"Kangoo"},
  {brand:"Renault", value:"Koleos", label:"Koleos"},
  {brand:"Renault", value:"Laguna", label:"Laguna"},
  {brand:"Renault", value:"Latitude", label:"Latitude"},
  {brand:"Renault", value:"Master", label:"Master"},
  {brand:"Renault", value:"Megane", label:"Megane"},
  {brand:"Renault", value:"Modus", label:"Modus"},
  {brand:"Renault", value:"Safrane", label:"Safrane"},
  {brand:"Renault", value:"Scenic", label:"Scenic"},
  {brand:"Renault", value:"Talisman", label:"Talisman"},
  {brand:"Renault", value:"Thalia", label:"Thalia"},
  {brand:"Renault", value:"Trafic", label:"Trafic"},
  {brand:"Renault", value:"Twingo", label:"Twingo"},
  {brand:"Renault", value:"Twizy", label:"Twizy"},
  {brand:"Renault", value:"Vel Satis", label:"Vel Satis"},
  {brand:"Renault", value:"Zoe", label:"Zoe"},
  {brand:"Rolls-Royce", value:"Sidabrinė", label:"Sidabrinė"},
  {brand:"Rover", value:"200", label:"200"},
  {brand:"Rover", value:"220", label:"220"},
  {brand:"Rover", value:"25", label:"25"},
  {brand:"Rover", value:"416", label:"416"},
  {brand:"Rover", value:"420", label:"420"},
  {brand:"Rover", value:"45", label:"45"},
  {brand:"Rover", value:"600", label:"600"},
  {brand:"Rover", value:"620", label:"620"},
  {brand:"Rover", value:"75", label:"75"},
  {brand:"Rover", value:"MGF", label:"MGF"},
  {brand:"Saab", value:"900", label:"900"},
  {brand:"Saab", value:"9000", label:"9000"},
  {brand:"Saab", value:"9-2X", label:"9-2X"},
  {brand:"Saab", value:"9-3", label:"9-3"},
  {brand:"Saab", value:"9-5", label:"9-5"},
  {brand:"Saab", value:"9-7X", label:"9-7X"},
  {brand:"Saab", value:"99", label:"99"},
  {brand:"Saturn", value:"VUE", label:"VUE"},
  {brand:"Scion", value:"TC", label:"TC"},
  {brand:"Scion", value:"XB", label:"XB"},
  {brand:"Seat", value:"Alhambra", label:"Alhambra"},
  {brand:"Seat", value:"Altea", label:"Altea"},
  {brand:"Seat", value:"Altea XL", label:"Altea XL"},
  {brand:"Seat", value:"Arosa", label:"Arosa"},
  {brand:"Seat", value:"Cordoba", label:"Cordoba"},
  {brand:"Seat", value:"Exeo", label:"Exeo"},
  {brand:"Seat", value:"Ibiza", label:"Ibiza"},
  {brand:"Seat", value:"Kita", label:"Kita"},
  {brand:"Seat", value:"Leon", label:"Leon"},
  {brand:"Seat", value:"Mii", label:"Mii"},
  {brand:"Seat", value:"Toledo", label:"Toledo"},
  {brand:"Secma", value:"F16", label:"F16"},
  {brand:"Shuanghuan", value:"CEO", label:"CEO"},
  {brand:"Shuanghuan", value:"Sceo", label:"Sceo"},
  {brand:"Skoda", value:"Citigo", label:"Citigo"},
  {brand:"Skoda", value:"Fabia", label:"Fabia"},
  {brand:"Skoda", value:"Octavia", label:"Octavia"},
  {brand:"Skoda", value:"Praktik", label:"Praktik"},
  {brand:"Skoda", value:"Rapid", label:"Rapid"},
  {brand:"Skoda", value:"Roomster", label:"Roomster"},
  {brand:"Skoda", value:"Superb", label:"Superb"},
  {brand:"Skoda", value:"Yeti", label:"Yeti"},
  {brand:"Smart", value:"Forfour", label:"Forfour"},
  {brand:"Smart", value:"Fortwo", label:"Fortwo"},
  {brand:"Smart", value:"Fortwo Coupe", label:"Fortwo Coupe"},
  {brand:"Smart", value:"Kupė (Coupe)", label:"Kupė (Coupe)"},
  {brand:"Smart", value:"Miesto", label:"Miesto"},
  {brand:"Smart", value:"Roadster", label:"Roadster"},
  {brand:"SsangYong", value:"Actyon", label:"Actyon"},
  {brand:"SsangYong", value:"Actyon Sports", label:"Actyon Sports"},
  {brand:"SsangYong", value:"Korando", label:"Korando"},
  {brand:"SsangYong", value:"Kyron", label:"Kyron"},
  {brand:"SsangYong", value:"Musso", label:"Musso"},
  {brand:"SsangYong", value:"Rexton", label:"Rexton"},
  {brand:"SsangYong", value:"Rodius", label:"Rodius"},
  {brand:"Subaru", value:"BRZ", label:"BRZ"},
  {brand:"Subaru", value:"Forester", label:"Forester"},
  {brand:"Subaru", value:"Impreza", label:"Impreza"},
  {brand:"Subaru", value:"Impreza  WRX", label:"Impreza  WRX"},
  {brand:"Subaru", value:"Justy", label:"Justy"},
  {brand:"Subaru", value:"Legacy", label:"Legacy"},
  {brand:"Subaru", value:"Levorg", label:"Levorg"},
  {brand:"Subaru", value:"Outback", label:"Outback"},
  {brand:"Subaru", value:"Trezia", label:"Trezia"},
  {brand:"Subaru", value:"Tribeca", label:"Tribeca"},
  {brand:"Subaru", value:"XV", label:"XV"},
  {brand:"Suzuki", value:"Alto", label:"Alto"},
  {brand:"Suzuki", value:"Grand Vitara", label:"Grand Vitara"},
  {brand:"Suzuki", value:"Ignis", label:"Ignis"},
  {brand:"Suzuki", value:"Jimny", label:"Jimny"},
  {brand:"Suzuki", value:"Kizashi", label:"Kizashi"},
  {brand:"Suzuki", value:"Liana", label:"Liana"},
  {brand:"Suzuki", value:"Samurai", label:"Samurai"},
  {brand:"Suzuki", value:"Splash", label:"Splash"},
  {brand:"Suzuki", value:"Swift", label:"Swift"},
  {brand:"Suzuki", value:"SX4", label:"SX4"},
  {brand:"Suzuki", value:"SX4 S-Cross", label:"SX4 S-Cross"},
  {brand:"Suzuki", value:"Vitara", label:"Vitara"},
  {brand:"Suzuki", value:"Wagon R+", label:"Wagon R+"},
  {brand:"Suzuki", value:"XL7", label:"XL7"},
  {brand:"Tata", value:"Indica", label:"Indica"},
  {brand:"Tesla", value:"Model S", label:"Model S"},
  {brand:"Toyota", value:"2000", label:"2000"},
  {brand:"Toyota", value:"4Runner", label:"4Runner"},
  {brand:"Toyota", value:"Auris", label:"Auris"},
  {brand:"Toyota", value:"Avalon", label:"Avalon"},
  {brand:"Toyota", value:"Avensis", label:"Avensis"},
  {brand:"Toyota", value:"Avensis Verso", label:"Avensis Verso"},
  {brand:"Toyota", value:"Aygo", label:"Aygo"},
  {brand:"Toyota", value:"Camry", label:"Camry"},
  {brand:"Toyota", value:"Carina", label:"Carina"},
  {brand:"Toyota", value:"Celica", label:"Celica"},
  {brand:"Toyota", value:"C-HR", label:"C-HR"},
  {brand:"Toyota", value:"Corolla", label:"Corolla"},
  {brand:"Toyota", value:"Corolla Verso", label:"Corolla Verso"},
  {brand:"Toyota", value:"Echo", label:"Echo"},
  {brand:"Toyota", value:"FJ Cruiser", label:"FJ Cruiser"},
  {brand:"Toyota", value:"GT 86", label:"GT 86"},
  {brand:"Toyota", value:"Hiace", label:"Hiace"},
  {brand:"Toyota", value:"Highlander", label:"Highlander"},
  {brand:"Toyota", value:"Hilux", label:"Hilux"},
  {brand:"Toyota", value:"iQ", label:"iQ"},
  {brand:"Toyota", value:"Land Cruiser", label:"Land Cruiser"},
  {brand:"Toyota", value:"Matrix", label:"Matrix"},
  {brand:"Toyota", value:"Mega Cruiser", label:"Mega Cruiser"},
  {brand:"Toyota", value:"MR 2", label:"MR 2"},
  {brand:"Toyota", value:"Paseo", label:"Paseo"},
  {brand:"Toyota", value:"Picnic", label:"Picnic"},
  {brand:"Toyota", value:"Previa", label:"Previa"},
  {brand:"Toyota", value:"Prius", label:"Prius"},
  {brand:"Toyota", value:"Prius+", label:"Prius+"},
  {brand:"Toyota", value:"ProAce", label:"ProAce"},
  {brand:"Toyota", value:"RAV4", label:"RAV4"},
  {brand:"Toyota", value:"Sienna", label:"Sienna"},
  {brand:"Toyota", value:"Solara", label:"Solara"},
  {brand:"Toyota", value:"Supra", label:"Supra"},
  {brand:"Toyota", value:"Tundra", label:"Tundra"},
  {brand:"Toyota", value:"Urban Cruiser", label:"Urban Cruiser"},
  {brand:"Toyota", value:"Venza", label:"Venza"},
  {brand:"Toyota", value:"Verso", label:"Verso"},
  {brand:"Toyota", value:"Verso-S", label:"Verso-S"},
  {brand:"Toyota", value:"Yaris", label:"Yaris"},
  {brand:"Toyota", value:"Yaris Verso", label:"Yaris Verso"},
  {brand:"Trabant", value:"601", label:"601"},
  {brand:"UAZ", value:"3303", label:"3303"},
  {brand:"UAZ", value:"3962", label:"3962"},
  {brand:"UAZ", value:"452", label:"452"},
  {brand:"UAZ", value:"469", label:"469"},
  {brand:"Vauxhall", value:"Astra", label:"Astra"},
  {brand:"Vauxhall", value:"Vectra", label:"Vectra"},
  {brand:"Volkswagen", value:"Amarok", label:"Amarok"},
  {brand:"Volkswagen", value:"Beetle", label:"Beetle"},
  {brand:"Volkswagen", value:"Bora", label:"Bora"},
  {brand:"Volkswagen", value:"Caddy", label:"Caddy"},
  {brand:"Volkswagen", value:"Caravelle", label:"Caravelle"},
  {brand:"Volkswagen", value:"Crafter", label:"Crafter"},
  {brand:"Volkswagen", value:"Eos", label:"Eos"},
  {brand:"Volkswagen", value:"Fox", label:"Fox"},
  {brand:"Volkswagen", value:"Golf", label:"Golf"},
  {brand:"Volkswagen", value:"Golf Plus", label:"Golf Plus"},
  {brand:"Volkswagen", value:"Golf Sportsvan", label:"Golf Sportsvan"},
  {brand:"Volkswagen", value:"Golf SportWagen", label:"Golf SportWagen"},
  {brand:"Volkswagen", value:"Jetta", label:"Jetta"},
  {brand:"Volkswagen", value:"Kaefer", label:"Kaefer"},
  {brand:"Volkswagen", value:"Kita", label:"Kita"},
  {brand:"Volkswagen", value:"Lt", label:"Lt"},
  {brand:"Volkswagen", value:"Lupo", label:"Lupo"},
  {brand:"Volkswagen", value:"Multivan", label:"Multivan"},
  {brand:"Volkswagen", value:"New Beetle", label:"New Beetle"},
  {brand:"Volkswagen", value:"Passat", label:"Passat"},
  {brand:"Volkswagen", value:"Passat Alltrack", label:"Passat Alltrack"},
  {brand:"Volkswagen", value:"Passat CC", label:"Passat CC"},
  {brand:"Volkswagen", value:"Phaeton", label:"Phaeton"},
  {brand:"Volkswagen", value:"Polo", label:"Polo"},
  {brand:"Volkswagen", value:"Routan", label:"Routan"},
  {brand:"Volkswagen", value:"Scirocco", label:"Scirocco"},
  {brand:"Volkswagen", value:"Sharan", label:"Sharan"},
  {brand:"Volkswagen", value:"Tiguan", label:"Tiguan"},
  {brand:"Volkswagen", value:"Touareg", label:"Touareg"},
  {brand:"Volkswagen", value:"Touran", label:"Touran"},
  {brand:"Volkswagen", value:"Transporter", label:"Transporter"},
  {brand:"Volkswagen", value:"Up", label:"Up"},
  {brand:"Volkswagen", value:"Vento", label:"Vento"},
  {brand:"Volvo", value:"244", label:"244"},
  {brand:"Volvo", value:"340", label:"340"},
  {brand:"Volvo", value:"440", label:"440"},
  {brand:"Volvo", value:"480", label:"480"},
  {brand:"Volvo", value:"850", label:"850"},
  {brand:"Volvo", value:"960", label:"960"},
  {brand:"Volvo", value:"C30", label:"C30"},
  {brand:"Volvo", value:"C70", label:"C70"},
  {brand:"Volvo", value:"Kita", label:"Kita"},
  {brand:"Volvo", value:"S40", label:"S40"},
  {brand:"Volvo", value:"S60", label:"S60"},
  {brand:"Volvo", value:"S70", label:"S70"},
  {brand:"Volvo", value:"S80", label:"S80"},
  {brand:"Volvo", value:"S90", label:"S90"},
  {brand:"Volvo", value:"V40", label:"V40"},
  {brand:"Volvo", value:"V40 Cross Country", label:"V40 Cross Country"},
  {brand:"Volvo", value:"V50", label:"V50"},
  {brand:"Volvo", value:"V60", label:"V60"},
  {brand:"Volvo", value:"V60 Cross Country ", label:"V60 Cross Country "},
  {brand:"Volvo", value:"V70", label:"V70"},
  {brand:"Volvo", value:"XC60", label:"XC60"},
  {brand:"Volvo", value:"XC70", label:"XC70"},
  {brand:"Volvo", value:"XC90", label:"XC90"},
  {brand:"Wanderer", value:"Kita", label:"Kita"},
  {brand:"ZAZ", value:"965", label:"965"},
  {brand:"ZAZ", value:"968", label:"968"},
  {brand:"ZAZ", value:"968M", label:"968M"}
];
