export const NAVIGATION_OPEN = 'NAVIGATION_OPEN';
export const NAVIGATION_CLOSE = 'NAVIGATION_CLOSE';

export const CLOCK_UPDATE = 'CLOCK_UPDATE';

export const REQUEST_WEATHER_SUCCESS = 'REQUEST_WEATHER_SUCCESS';
export const REQUEST_WEATHER_ERROR = 'REQUEST_WEATHER_ERROR';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOCALE_CHANGED = 'LOCALE_CHANGED';
